<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223062649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE appointment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE artist_post ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE artist_post ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_58a76f3b4f4e2a1e RENAME TO IDX_E634EA12B7970CF8');
        $this->addSql('ALTER INDEX idx_40ef1a7c95a3bb01 RENAME TO IDX_34E4C364FCC65D1B');
        $this->addSql('ALTER INDEX idx_40ef1a7ced5ca9e6 RENAME TO IDX_34E4C364ED5CA9E6');
        $this->addSql('ALTER TABLE artist_post_comment ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE artist_post_comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_5c2b88f54b89032c RENAME TO IDX_410D0BDA4B89032C');
        $this->addSql('ALTER INDEX idx_5c2b88f5a76ed395 RENAME TO IDX_410D0BDAA76ED395');
        $this->addSql('DROP INDEX uniq_post_user');
        $this->addSql('ALTER TABLE artist_post_rating ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE artist_post_rating ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_a4b44c9b4b89032c RENAME TO IDX_C19174004B89032C');
        $this->addSql('ALTER INDEX idx_a4b44c9ba76ed395 RENAME TO IDX_C1917400A76ED395');
        $this->addSql('ALTER TABLE artist_profile ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE artist_profile ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_artist_profile_category RENAME TO IDX_3618F43812469DE2');
        $this->addSql('ALTER TABLE availability ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE availability ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE home_page_settings ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE home_page_settings ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE service ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE service ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE service_category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE service_category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX idx_user_password_reset_token_hash');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment ALTER id SET DEFAULT nextval(\'appointment_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE appointment ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE artist_post ALTER id SET DEFAULT nextval(\'artist_post_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE artist_post ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_e634ea12b7970cf8 RENAME TO idx_58a76f3b4f4e2a1e');
        $this->addSql('ALTER TABLE artist_post_comment ALTER id SET DEFAULT nextval(\'artist_post_comment_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE artist_post_comment ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_410d0bdaa76ed395 RENAME TO idx_5c2b88f5a76ed395');
        $this->addSql('ALTER INDEX idx_410d0bda4b89032c RENAME TO idx_5c2b88f54b89032c');
        $this->addSql('ALTER TABLE artist_post_rating ALTER id SET DEFAULT nextval(\'artist_post_rating_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE artist_post_rating ALTER id DROP IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX uniq_post_user ON artist_post_rating (post_id, user_id)');
        $this->addSql('ALTER INDEX idx_c19174004b89032c RENAME TO idx_a4b44c9b4b89032c');
        $this->addSql('ALTER INDEX idx_c1917400a76ed395 RENAME TO idx_a4b44c9ba76ed395');
        $this->addSql('ALTER INDEX idx_34e4c364ed5ca9e6 RENAME TO idx_40ef1a7ced5ca9e6');
        $this->addSql('ALTER INDEX idx_34e4c364fcc65d1b RENAME TO idx_40ef1a7c95a3bb01');
        $this->addSql('ALTER TABLE artist_profile ALTER id SET DEFAULT nextval(\'artist_profile_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE artist_profile ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_3618f43812469de2 RENAME TO idx_artist_profile_category');
        $this->addSql('ALTER TABLE availability ALTER id SET DEFAULT nextval(\'availability_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE availability ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE home_page_settings ALTER id SET DEFAULT nextval(\'home_page_settings_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE home_page_settings ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE service ALTER id SET DEFAULT nextval(\'service_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE service ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE service_category ALTER id SET DEFAULT nextval(\'service_category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE service_category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_user_password_reset_token_hash ON "user" (password_reset_token_hash)');
    }
}
