<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316145812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE did_you_know_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, is_approved BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_85CABB564B89032C ON did_you_know_comment (post_id)');
        $this->addSql('CREATE INDEX IDX_85CABB56A76ED395 ON did_you_know_comment (user_id)');
        $this->addSql('CREATE INDEX idx_dyk_comment_approved ON did_you_know_comment (is_approved, created_at)');
        $this->addSql('CREATE TABLE did_you_know_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content TEXT NOT NULL, image_url VARCHAR(255) DEFAULT NULL, seo_title VARCHAR(255) DEFAULT NULL, meta_description TEXT DEFAULT NULL, canonical_url VARCHAR(255) DEFAULT NULL, robots_directive VARCHAR(64) DEFAULT NULL, og_title VARCHAR(255) DEFAULT NULL, og_description TEXT DEFAULT NULL, og_image_url VARCHAR(255) DEFAULT NULL, og_image_alt VARCHAR(255) DEFAULT NULL, is_published BOOLEAN DEFAULT false NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_did_you_know_post_published ON did_you_know_post (is_published, published_at)');
        $this->addSql('CREATE TABLE did_you_know_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, post_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_676B40F94B89032C ON did_you_know_rating (post_id)');
        $this->addSql('CREATE INDEX IDX_676B40F9A76ED395 ON did_you_know_rating (user_id)');
        $this->addSql('ALTER TABLE did_you_know_comment ADD CONSTRAINT FK_85CABB564B89032C FOREIGN KEY (post_id) REFERENCES did_you_know_post (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE did_you_know_comment ADD CONSTRAINT FK_85CABB56A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE did_you_know_rating ADD CONSTRAINT FK_676B40F94B89032C FOREIGN KEY (post_id) REFERENCES did_you_know_post (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE did_you_know_rating ADD CONSTRAINT FK_676B40F9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artist_post_service ADD CONSTRAINT FK_34E4C364FCC65D1B FOREIGN KEY (artist_post_id) REFERENCES artist_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE artist_post_service ADD CONSTRAINT FK_34E4C364ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE artist_profile ADD CONSTRAINT FK_3618F43812469DE2 FOREIGN KEY (category_id) REFERENCES service_category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_9228E07D2F85CDC1 ON artist_profile_service (artist_profile_id)');
        $this->addSql('CREATE INDEX IDX_9228E07DED5CA9E6 ON artist_profile_service (service_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE did_you_know_comment DROP CONSTRAINT FK_85CABB564B89032C');
        $this->addSql('ALTER TABLE did_you_know_comment DROP CONSTRAINT FK_85CABB56A76ED395');
        $this->addSql('ALTER TABLE did_you_know_rating DROP CONSTRAINT FK_676B40F94B89032C');
        $this->addSql('ALTER TABLE did_you_know_rating DROP CONSTRAINT FK_676B40F9A76ED395');
        $this->addSql('DROP TABLE did_you_know_comment');
        $this->addSql('DROP TABLE did_you_know_post');
        $this->addSql('DROP TABLE did_you_know_rating');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844B7970CF8');
        $this->addSql('ALTER TABLE artist_post_service DROP CONSTRAINT FK_34E4C364FCC65D1B');
        $this->addSql('ALTER TABLE artist_post_service DROP CONSTRAINT FK_34E4C364ED5CA9E6');
        $this->addSql('ALTER TABLE artist_profile DROP CONSTRAINT FK_3618F43812469DE2');
        $this->addSql('ALTER TABLE artist_profile_service DROP CONSTRAINT FK_9228E07D2F85CDC1');
        $this->addSql('DROP INDEX IDX_9228E07D2F85CDC1');
        $this->addSql('DROP INDEX IDX_9228E07DED5CA9E6');
    }
}
